# https://github.com/googleapis/repo-automation-bots/tree/master/packages/sync-repo-settings

permissionRules:
    # Team slug to add to repository permissions
  - team: api-kms
    # Access level required, one of push|pull|admin
    permission: push
